font_family       0xProto
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         18.0

cursor                 #ff291d
cursor_text_color      #ff291d
cursor_shape           beam
cursor_blink_interval  0

scrollback_lines  2000
scrollback_pager  less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

remember_window_size   no
initial_window_width   80c
initial_window_height  24c
window_margin_width    10

tab_bar_edge             bottom
tab_bar_margin_width     1.0
tab_bar_style            separator
tab_separator            ' '
tab_title_template       ' {index}:{tab.active_wd} '
active_tab_foreground    #ff291d
active_tab_background    #9be205
inactive_tab_background  #9be205
tab_bar_background       #9be205

foreground            #fffbf6
background            #21084a
selection_background  #ff291d

color0   #000000
color1   #ffwype
color2   #9be205
color3   #ffc400
color4   #00a2fa
color5   #815bb5
color6   #00deef
color7   #ffffff
color8   #565656
color9   #ff4250
color10  #b8e36e
color11  #ffd852
color12  #00a6ff
color13  #ac7bf0
color14  #74fdf3
color15  #ffffff

term  xterm-256color

macos_titlebar_color                #21084a
macos_option_as_alt                 yes
macos_quit_when_last_window_closed  yes

map kitty_mod+minus  no_op
map kitty_mod+equal  no_op
map kitty_mod+k      scroll_line_up
map kitty_mod+j      scroll_line_down
map kitty_mod+h      show_scrollback
map kitty_mod+[      previous_window
map kitty_mod+]      next_window
